### ISSUE TITLE
Adding Information  for  Beginner in  Perl 

### ISSUE THREAD

**Issue by Ultron03** [MunGell/awesome-for-beginners#1170]

**Comment by GauravPatil8778** [comment]
I will add some introductory part of perl!!

**Comment by abhint1** [comment]
I can some introductory part of perl , please assign it to me

**Comment by SusavanMondal** [comment]
Hello,
I can contribute to my best in this issue. Can you please assign this task to me?

**Comment by Dhanunjay18** [comment]
Hello i want to add hacktoberfest label to it @Rohitchaudhary13

**Comment by adarsh1114** [comment]
Hello,
I want to add some more information about Perl.

**Comment by Marionkay-star** [comment]
I want to add so more information

**Comment by sammyhori** [comment]
Hi all, thanks for the offers of help!

Unfortunately, this repository is not for hosting introductory tutorials to any language, rather it lists projects with issues that beginners to a language can attempt to fix.

If there was a repository introducing people to perl, that fit the requirements currently set out in the contributing guide then it could be added. Otherwise this project should stick to just hosting a list of repos and avoid trying to host introductory content as well (scope creep).
