### ISSUE TITLE
Are these projects really beginners-friendly?

### ISSUE THREAD

**Issue by Linkerist** [MunGell/awesome-for-beginners#215]
Well, this is an awesome repo.  

But, is really these projects beginner-friendly?  

For example, *electron* is quite a big project for C++ beginners, the label we sticked is *good-beginner-issue*, but beginners' issues may be similarly, sometimes repeated issues proposed over and over again.  

Another example is *tensorflow*, an open source machine learning framework. It is an awesome project indeed, but our label is *contributions welcome*. A greenhand programmer who knows C++ well, meanwhile knows little machine learning will not be welcomed to make inferior quality contribution for *tensorflow*.  

How do you see it?

**Comment by aryanaces** [comment]
Yea in my opinion these projects are not for absolute beginners , in fact they are for the intermediate developers who have already building some projects .
But this repo can still be useful for the people who are learning to add pull requests , by simply adding some link/information that they think might be helpful for the beginners .

**Comment by anjaliparmar** [comment]
Hello,
I'm learning python, and i want to contribute in your project.

**Comment by MunGell** [comment]
Hi @Linkerist 

Thanks for your question – it is relevant and needs to be clarified.

The original idea of this list was to collect links where beginner contributors (but not beginner developers) will be able to become part of open source community.

I would prefer to stick to this idea. I don't think absolute beginner developer will benefit from participating in open source and vice versa. 
However I believe that even a junior developer could make an impact for some open source projects out there.

The list has grown a lot since I've created it originally. If you see a link that does not match the idea above - please let me know or create a PR.

I might need to update the contributing guidelines to clarify what "beginner-friendly" actually means.

If anyone has anything to add to this conversation - I will be glad to hear other opinions.
I will leave this issue open for some time to keep it visible.

**Comment by oxr463** [comment]
But perhaps there may be some really talented developers who are just new to open source.

And even in large projects, there are simple tasks that need doing but none of the core developers have time for.

> Many hands make light work.

**Comment by albertcamin** [comment]
Hi! I'm just starting to learn Python and how to use Github. I will try to follow this project and contribute

**Comment by zootechdrum** [comment]
Hello I would also like to contribute to your project. Where can I start?

**Comment by MunGell** [comment]
Sorry, I have to lock this issue as it gets irrelevant comments e.g. how to contribute to this repository. I pinned it in the issue list.

Please open a new issue if you have something to say on the topic and reference this issue for linking.
